### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jskswamy** [thoughtworks/talisman#124]
Unable to do git commit, talisman crashes with following error

```bash
Your version of Talisman is outdated. Updating Talisman to v0.4.8
Downloading latest talisman binary...
talisman_darwin_amd64: OK

Talisman binary updated successfully!
panic: runtime error: index out of range

goroutine 1 [running]:
talisman/git_repo.GitRepo.stagedFiles(0xc000024064, 0x4d, 0x203000, 0x100000000000008, 0x0)
        /go/src/github.com/thoughtworks/talisman/git_repo/git_repo.go:183 +0x2c7
talisman/git_repo.GitRepo.GetDiffForStagedFiles(0xc000024064, 0x4d, 0xc000024064, 0x4d, 0x0)
        /go/src/github.com/thoughtworks/talisman/git_repo/git_repo.go:43 +0x50
main.(*PreCommitHook).GetRepoAdditions(0xc0000bfd50, 0xf, 0xc0000bfd90, 0x1)
        /go/src/github.com/thoughtworks/talisman/pre_commit_hook.go:18 +0x42
main.run(0x1484f40, 0xc00000e010, 0x0, 0x7ffeefbfe66b, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/thoughtworks/talisman/talisman.go:121 +0x3c4
main.main()
        /go/src/github.com/thoughtworks/talisman/talisman.go:90 +0x5eb
```

> Even though I see `Talisman binary updated successfully!` message in the log, on next commit talisman is trying to download again

**Comment by harinee** [comment]
@jskswamy Thanks for the PR.
@vhasus @aaquibzama-tw If you are happy with it, could you please create a release with the patch?

**Comment by harinee** [comment]
@jskswamy the fix is released now
